#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width        2 
bspc config window_gap          0 # 12

bspc config top_padding 0

#bspc config active_border_color "#6272a4"
bspc config focused_border_color "#F51720"
bspc config normal_border_color "#848484"
#bspc config focused_border_color \#C3C3C3
#bspc config active_border_color \#E84F4F

#bspc config focused_border_color \#33E6FF

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "MEGAsync" state=floating border=off


polybar -r polybarra &
